const REQUESTS = [
  {
    "id": "beb8ac8d-b8a3-4d17-8066-8e104d380dc8",
    "name": "just just section",
    "totalScore": 1500,
    "passingScore": 1290,
    "templateType": "form",
    "template": {
      "page": 0,
      "display": "form",
      "components": [
        {
          "id": "etynnjx",
          "key": "justJustSectionTextFie",
          "case": "",
          "mask": false,
          "tags": [],
          "type": "textfield",
          "input": true,
          "label": "Just just section text field",
          "logic": [],
          "hidden": false,
          "prefix": "",
          "suffix": "",
          "unique": false,
          "widget": {
            "type": "input"
          },
          "dbIndex": false,
          "overlay": {
            "top": "",
            "left": "",
            "page": "",
            "style": "",
            "width": "",
            "height": ""
          },
          "tooltip": "",
          "disabled": false,
          "multiple": false,
          "redrawOn": "",
          "tabindex": "",
          "validate": {
            "json": "",
            "custom": "",
            "unique": false,
            "pattern": "",
            "multiple": false,
            "required": false,
            "maxLength": "",
            "minLength": "",
            "customMessage": "",
            "customPrivate": false,
            "strictDateValidation": false
          },
          "autofocus": false,
          "encrypted": false,
          "hideLabel": false,
          "inputMask": "",
          "inputType": "text",
          "modalEdit": false,
          "protected": false,
          "refreshOn": "",
          "tableView": true,
          "attributes": {},
          "errorLabel": "",
          "persistent": true,
          "properties": {},
          "spellcheck": true,
          "validateOn": "change",
          "clearOnHide": true,
          "conditional": {
            "eq": "",
            "json": "",
            "show": null,
            "when": null
          },
          "customClass": "",
          "description": "",
          "inputFormat": "plain",
          "placeholder": "",
          "defaultValue": "",
          "labelPosition": "top",
          "showCharCount": false,
          "showWordCount": false,
          "calculateValue": "",
          "calculateServer": false,
          "customConditional": "",
          "allowMultipleMasks": false,
          "customDefaultValue": "",
          "allowCalculateOverride": false
        },
        {
          "id": "e4mnc8l",
          "key": "numberFieldForJustSection",
          "mask": false,
          "tags": [],
          "type": "number",
          "input": true,
          "label": "Number field for just section",
          "logic": [],
          "hidden": false,
          "prefix": "",
          "suffix": "",
          "unique": false,
          "widget": {
            "type": "input"
          },
          "dbIndex": false,
          "overlay": {
            "top": "",
            "left": "",
            "page": "",
            "style": "",
            "width": "",
            "height": ""
          },
          "tooltip": "",
          "disabled": false,
          "multiple": false,
          "redrawOn": "",
          "tabindex": "",
          "validate": {
            "max": "",
            "min": "",
            "json": "",
            "step": "any",
            "custom": "",
            "unique": false,
            "integer": "",
            "multiple": false,
            "required": false,
            "customMessage": "",
            "customPrivate": false,
            "strictDateValidation": false
          },
          "autofocus": false,
          "delimiter": false,
          "encrypted": false,
          "hideLabel": false,
          "modalEdit": false,
          "protected": false,
          "refreshOn": "",
          "tableView": false,
          "attributes": {},
          "errorLabel": "",
          "persistent": true,
          "properties": {},
          "spellcheck": true,
          "validateOn": "change",
          "clearOnHide": true,
          "conditional": {
            "eq": "",
            "json": "",
            "show": null,
            "when": null
          },
          "customClass": "",
          "description": "",
          "inputFormat": "plain",
          "placeholder": "",
          "defaultValue": null,
          "labelPosition": "top",
          "showCharCount": false,
          "showWordCount": false,
          "calculateValue": "",
          "requireDecimal": false,
          "calculateServer": false,
          "customConditional": "",
          "allowMultipleMasks": false,
          "customDefaultValue": "",
          "allowCalculateOverride": false
        },
        {
          "id": "eaza55",
          "key": "submit",
          "size": "md",
          "tags": [],
          "type": "button",
          "block": false,
          "input": true,
          "label": "Submit",
          "logic": [],
          "theme": "primary",
          "action": "submit",
          "hidden": false,
          "prefix": "",
          "suffix": "",
          "unique": false,
          "widget": {
            "type": "input"
          },
          "dbIndex": false,
          "overlay": {
            "top": "",
            "left": "",
            "page": "",
            "style": "",
            "width": "",
            "height": ""
          },
          "tooltip": "",
          "disabled": false,
          "leftIcon": "",
          "multiple": false,
          "redrawOn": "",
          "shortcut": "",
          "tabindex": "",
          "validate": {
            "custom": "",
            "unique": false,
            "multiple": false,
            "required": false,
            "customPrivate": false,
            "strictDateValidation": false
          },
          "autofocus": false,
          "encrypted": false,
          "hideLabel": false,
          "modalEdit": false,
          "protected": false,
          "refreshOn": "",
          "rightIcon": "",
          "tableView": false,
          "attributes": {},
          "errorLabel": "",
          "persistent": false,
          "properties": {},
          "validateOn": "change",
          "clearOnHide": true,
          "conditional": {
            "eq": "",
            "json": "",
            "show": null,
            "when": null
          },
          "customClass": "",
          "description": "",
          "placeholder": "",
          "defaultValue": null,
          "dataGridLabel": true,
          "labelPosition": "top",
          "showCharCount": false,
          "showWordCount": false,
          "calculateValue": "",
          "showValidations": false,
          "disableOnInvalid": false,
          "customConditional": "",
          "allowMultipleMasks": false,
          "customDefaultValue": "",
          "allowCalculateOverride": false
        }
      ],
      "totalScore": 1500,
      "passingScore": 1290
    },
    "data": {
      "submit": true,
      "justJustSectionTextFie": "qweqqewew 97979879797 9879 79797 ",
      "numberFieldForJustSection": 56546546464646545000
    },
    "sme": {
      "id": "16de9e8e-8460-4d89-aec3-7847f446d813",
      "name": "Section Just Sme"
    },
    "assigned": false
  }
];

export class SingleAccreditationRequestState {
  requests: {
    id: string,
    name: string,
    totalScore: number,
    passingScore: number,
    templateType: string,
    template: any,
    data: any,
    sme: any,
    assigned: boolean,
    review: any,
    reviewStatus: any,
    reviewHistory: any,
    reassignmentStatus: any,
  }[] = [];
}
