export { LoginComponent } from "./login/login.component";
export { SurveysComponent } from "./surveys/surveys.component";
export { CoffeeElectionComponent } from "./coffee-election/coffee-election.component";
// export { RegisterComponent, ConfirmDialogComponent } from "./register/register.component";
export { RegisterComponent } from "./register/register.component";
export { AuthGuard } from '../_gaurds/auth.gaurd';
export { UsersComponent } from "./users/users.component";
export { CreateSurveyComponent } from "./create-survey/create-survey.component";
export { FipHomeComponent } from "./fip-home/fip-home.component";
export { FipEligibilityComponent } from "./fip-eligibility/fip-eligibility.component";
export { FipQualificationComponent } from "./fip-qualification/fip-qualification.component";
export { AccreditationRequestComponent, AssignTask, IntimateFip } from "./accreditation-request/accreditation-request.component";
export { SmeComponent } from "./sme/sme.component";
export { AddSmeComponent } from "./add-sme/add-sme.component";
export { AddUserComponent } from './add-user/add-user.component';
export { AccreditationCommentsMatrixComponent } from './accreditation-comments-matrix/accreditation-comments-matrix.component';
export { EligibilityRequestsComponent } from './eligibility-requests/eligibility-requests.component';
export { ProposalSectionsComponent } from './proposal-sections/proposal-sections.component';
export { AddProposalSectionComponent } from './add-proposal-section/add-proposal-section.component';
export { CreateProposalFormComponent } from './create-proposal-form/create-proposal-form.component';
export { ProposalFormsComponent } from './proposal-forms/proposal-forms.component';
export { ProjectPlanComponent } from './project-plan/project-plan.component';
export { TreeComponent } from './tree/tree.component';
export { ConfirmDialogComponent } from './confirm-dialog/confirm-dialog.component';
