const QPR = {
  "id": "6db74d3a-9ec3-4c61-91f6-e071531de883",
  "data": null,
  "amount": null,
  "comments": null,
  "status": "Not Initiated",
  "subStatus": null,
  "payeesName": null,
  "payeesAddress": null,
  "bankName": null,
  "bankAddress": null,
  "payeesAccount": null,
  "swiftCode": null,
  "specialPaymentInstruction": null,
}

export class AdvanceLiquidationItemState {
  data: {
    "id": any,
    "data": any,
    "amount": any,
    "comments": any,
    "status": any,
    "subStatus": any,
    "payeesName": any,
    "payeesAddress": any,
    "bankName": any,
    "bankAddress": any,
    "payeesAccount": any,
    "swiftCode": any,
    "specialPaymentInstruction": any,
    "fipSoes": {
      "activityId": string,
      "vendorName": string,
      "invoiceAmount": number,
      "dateOfPayment": string,
      "paidAmount": number,
      "chequeNumber": string,
      "remarks": string,
      "soeType": string,
      "id": string,
    },
    "ndrmfSoes": {
      "activityId": string,
      "vendorName": string,
      "invoiceAmount": number,
      "dateOfPayment": string,
      "paidAmount": number,
      "chequeNumber": string,
      "remarks": string,
      "soeType": string,
      "id": string,
    },
  } = null;
}
