const DISBURSMENT = null;

export class SingleGrantDisbursmentsState {
  disbursment: {
    proposalName: string,
    implementationPlan: any,
    initiatedBy: any,
    initialAdvance: {
      status: any,
      subStatus: any,
      amount: any,
      data: any,
      id: any,
      initialAdvanceReviewsList: any
      advanceLiquidationItem: any,
      payeesName: any,
      payeesAddress: any,
      bankName: any,
      bankAddress: any,
      payeesAccount: any,
      swiftCode: any,
      specialPaymentInstruction: any,
      showNoti: any,
    },
    quarterAdvanceList: {
      status: any,
      amount: any,
      data: {
        _id: any,
        addRf: any,
        title: any,
        amount: any,
        clubId: any,
        clubbed: any,
        quarters: any,
        totalCost: any,
        mainCostId: any,
        parentCosts: any,
        ndrmfExpenditureLastQuarter: any,
        fipExpenditureLastQuarter: any,
        ndrmfExpenditureCurrentQuarter: any,
        fipExpenditureCurrentQuarter: any,
        ndrmfTotalBudgetAllocation: any,
        fipTotalBudgetAllocation: any,
        fipQuarterBudgetAllocation: any,
        ndrmfQuarterBudgetAllocation: any,
        fipExpenditureTillDate: any,
        ndrmfExpenditureTillDate: any,
        totalRequirementForTheProject: any,
        ndrmfVarience: any,
        fipVarience: any,
        ndrmfRemainingBudget: any,
        fipRemainingBudget: any,
      }[],
      id: any,
      subStatus: any,
      quarterAdvanceReviewsList: any,
      advanceLiquidationItem: any,
      payeesName: any,
      payeesAddress: any,
      bankName: any,
      bankAddress: any,
      payeesAccount: any,
      swiftCode: any,
      specialPaymentInstruction: any,
      quarter: any,
      showNoti: any,
    }[],
    assigned: any,
    id: any,
    initAdvanceStatus: any,
    owner: any,
    quarterAdvanceStatus: any,
    status: any,
    subStatus: any,
    selectionType: any
  } = DISBURSMENT;
}
