const REQUESTS = [
  {
    userRef: 'dummy@user.com',
    formSubmitData: { 'radioa': 'yes', 'radiob': 'yes', 'radioc': 'no', 'radiod': 'yes', },
    formData: {},
    status: 'pending',
    formIdentity: 'quali-os',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'qualification',
    userUpdateFlag: true,
  },
  {
    userRef: 'dummy@user.com',
    formSubmitData: { "CO1984CA2017": true, "SRA1860": false, "VSWOO1961": true, "TA1882": false, "EADGOP": false, "BTUN": false, "submit": true, "CO1984CA2017-status": "active", "VSWOO1961-status": "inactive" },
    formData: {},
    status: 'pending',
    formIdentity: 'eligibility-registartion',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'eligibility',
    userUpdateFlag: false,
  },
  {
    userRef: 'dummy@user.com',
    formSubmitData: { "radiob1a": "yes", "radiob1b": "yes", "radiob1c": "yes", "radiob1d": "no", "radiob1e": "", "radiob2a": "", "radiob2b": "", "radiob2c": "", "radiob2d": "", "radiob2e": "", "radiob3a": "", "radiob3b": "", "radiob3c": "", "radiob3d": "", "radiob3e": "", "radiob3f": "yes", "radiob3g": "yes", "submit": true },
    formData: {},
    status: 'pending',
    formIdentity: 'quali-rlr',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'qualification',
    userUpdateFlag: true,
  },
  {
    userRef: 'dummy@user.com',
    formSubmitData: { "radiof1a": "yes", "radiof1b": "yes", "radiof1c": "", "radiof1d": "yes", "radiof1e": "no", "radiof1f": "", "radiof1g": "", "radiof2a": "yes", "radiof2b": "yes", "radiof2c": "yes", "radiof2d": "yes", "radiof2e": "", "submit": true },
    formData: {},
    status: 'pending',
    formIdentity: 'quali-gia',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'qualification',
    userUpdateFlag: true,
  },
  {
    userRef: 'dummy@user.com',
    formSubmitData: { "radiod1a": "yes", "radiod1b": "yes", "radiod1c": "", "radiod1d": "yes", "radiod1e": "", "radiod1f": "", "radiod1g": "yes", "radiod2a": "yes", "radiod2b": "yes", "radiod2c": "yes", "radiod2d": "yes", "radiod2e": "yes", "radiod2f": "yes", "radiod2g": "yes", "radiod2h": "yes", "radiod3a": "", "radiod3b": "", "radiod3c": "", "radiod3d": "", "radiod3e": "", "radiod3f": "", "radiod3g": "", "radiod3h": "", "radiod4a": "", "radiod4b": "", "radiod4c": "", "radiod4d": "", "radiod4e": "", "textd4f": "tahsdo oiuasod ", "textd4g": "09809 asdj", "textd4h": "paosid ", "radiod5a": "yes", "radiod5b": "yes", "radiod5c": "", "radiod5d": "yes", "radiod5e": "yes", "submit": true },
    formData: {},
    status: 'pending',
    formIdentity: 'quali-proc',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'qualification',
    userUpdateFlag: false,
  },
  {
    userRef: 'dummy@user.com',
    formSubmitData: { 
      "radioea": "yes", 
    "radioeb": "yes", "radioec1": "yes", 
    "radioec2": "yes", 
    "radioec3": "no",
     "radioec4": "no", "radioec5": "no", "radioec6": "no", "submit": true },
    formData: {},
    status: 'pending',
    formIdentity: 'quali-ess',
    startDate: '',
    endDate: '',
    previousReview: null,
    currentReview: null,
    requestKey: 'qualification',
    userUpdateFlag: false,
  },
]

export class AccreditationRequestState {
  requests: {
    userRef: string,
    formSubmitData: any,
    formData: any,
    status: string,
    formIdentity: string,
    startDate: string,
    endDate: string,
    previousReview: string,
    currentReview: string,
    requestKey: string,
    userUpdateFlag: boolean,
  }[] = REQUESTS;
}
